### ISSUE TITLE
Radarr error 

### ISSUE THREAD

**Issue by calm3285** [zakkarry/retraktarr#11]
I been using this script to make backups without a problem, but today i get this error

retraktarr -a

retraktarr v1.1.2
Validating Configuration File: /home/med/.config/retraktarr.conf

[Radarr]
Traceback (most recent call last):
  File "/home/med/.local/bin/retraktarr", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/med/.local/lib/python3.12/site-packages/retraktarr/retraktarr.py", line 174, in main
    trakt_api.add_to_list(
  File "/home/med/.local/lib/python3.12/site-packages/retraktarr/api/trakt.py", line 469, in add_to_list
    needed_ids = self.del_from_list(
                 ^^^^^^^^^^^^^^^^^^^
  File "/home/med/.local/lib/python3.12/site-packages/retraktarr/api/trakt.py", line 323, in del_from_list
    data[media_type.rstrip("s")]["ids"].get(
    ~~~~^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'movie'

**Comment by zakkarry** [comment]
It seems to be related to the trakt API returns, it might be necessary to either create a new list or use the --wipe function to clear the list and readd everything.

Do you have separate lists for TV and movies or combined? It may also be possible something listed in your radarr instance is a TV movie or something and does not have the expected associated key's.

**Comment by calm3285** [comment]
I use this script to merge all my lists in to one, movies and shows

i fix it with deleting the list

[Radarr]
Trakt.tv Error (404): https://trakt.tv/users/angelss19/lists/all not found...

Creating public Trakt.tv list: (all)...

Number of Movies Added: 285
Number of Movies Not Found: 0
Number of Movies Listed: 285
Total Movies: 285

[Sonarr]
Number of Shows Added: 63
Number of Shows Not Found: 0
Number of Shows Listed: 348
Total Series: 63
