### ISSUE TITLE
feat(request): add argument to filter by "missing" status in arrs

### ISSUE THREAD

**Issue by WatPow** [zakkarry/retraktarr#8]
Hello,

I am interested in using retraktarr to synchronize my Radarr and Sonarr lists with Trakt. I would like to request a feature that allows syncing only the items marked as "missing" in Radarr and Sonarr to the Trakt list. This feature would be invaluable for users like me who manage files on a seedbox and delete them post-transfer, ensuring that only the necessary "missing" movies and series are tracked and added to Trakt.

Thank you for considering this feature request!

**Comment by zakkarry** [comment]
Good addition, will look into getting this implemented - hopefully this weekend, time permitting. Thanks.

**Comment by WatPow** [comment]
I still tried using custom tags for Radarr as you advised, and it seems to work (for my use at least). I added a "imported" tag with the conditions: "not monitored" and "present in root path" (if it's in the root path, it means it was imported from the download client, so it's considered imported.

I sync the list with Trakt using the -p parameter and boom, it works.

For Sonarr, it's a different story, what a headache... The same custom tags don't work because a series is always "monitored" as long as it's not "ended", which means as long as it continues to be aired, it retains its "monitored" status. And for the mandatory presence in the root path, if I do that, it syncs 100% of the series. Oh, but wait... It's hitting me as I write... If I set the condition that the series **must not** be in the root path and I check the "delete empty folders after file deletions" parameter, it might just work, I'm going to try :D

**Comment by zakkarry** [comment]
For Radarr, typically using Size on Disk for missing is what I've seen recommended. Sonarr, I just don't know.

As we discussed on Discord, I'm not entirely sure what should or should not constitute a "missing" qualification for Sonarr, the main issue being that every week for a short time there will be missing episodes. Percentage of Episodes is a possibility, but once again this is a potentially fluid metric to base this off. I'm going to look into Radarr's implementation now, and think more about Sonarr.

Thoughts are welcome on potential Sonarr integrations for missing.

**Comment by zakkarry** [comment]
Pending Sonarr (if possible) implementation. Radarr is done, about to push 1.0.7 for this. 

Feel free to test, or update using pip once 1.0.7 is on pypi

**Comment by zakkarry** [comment]
Radarr implementation is live....

use `--missing` in conjunction with any other arguments as you normally would.

**Comment by zakkarry** [comment]
No viable use with sonarr in use-cases has been found, closing this. Any future issues for this flag in sonarr will need to provide some way for it to be done that makes sense.
